### ISSUE TITLE
injector should close objects in reverse order of creation.

### ISSUE THREAD

**Issue by NicolasAubry** [delvelabs/easyinject#4]
If the injector creates two objects, and one depend on the other (like asyncio.loop and aiohttp.ClientSession), then closing the loop before closing the client session can cause problems. A simple fix for this issue would be to prepend close methods to the list:
`python

    def _record_closeable(self, value):  
        if not inspect.isclass(value) and hasattr(value, 'close') and inspect.isroutine(value.close): 
            self.___close_list.insert(0, value.close)  
`

**Comment by lphuberdeau** [comment]
Issue is resolved in master. To be included in 0.3.
